### ISSUE TITLE
src/qcg/pilotjob/launcher/__init__.py missing

### ISSUE THREAD

**Issue by LourensVeen** [vecma-project/QCG-PilotJob#107]
I'm getting import errors because qcg.pilotjob.launcher isn't a valid Python module, since its __init__.py is missing.

It looks to be only an issue when I try to run tests via setuptools (i.e. `python setup.py test` in my software); setuptools actually still uses easy-install and somehow it's a problem there but not for pip. So I can work around it by pip installing QCG-PJ first, but of course it's still not correct Python to have that file missing.

**Comment by pkopta** [comment]
Thanks for notification - fixed in #108 (merged into develop).

**Comment by LourensVeen** [comment]
Great, thanks!
