### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by LourensVeen** [vecma-project/QCG-PilotJob#138]
The root directory of this repository contains a LICENSE file with the Apache License 2.0 in it, and a LICENSE.txt file with the GPLv3. This needs clarification. Is QCG-PilotJob licensed under both of these? Or was it originally GPL and now Apache? Please add a statement to the README that explains the licensing situation.

**Comment by bartoszbosak** [comment]
QCG-PilotJob is released uner Apache 2.0. We have already removed the misleading LICENSE.txt file.
