### ISSUE TITLE
Documentation on execution model unclear and/or outdated

### ISSUE THREAD

**Issue by LourensVeen** [vecma-project/QCG-PilotJob#155]
In https://github.com/vecma-project/QCG-PilotJob/blob/develop/docs/fileinterface.rst in the description of the `submit` command, it says about `model`:

> the model of execution, currently only threads explicit model is supported which should be used for OpenMP jobs; if not defined - the default, dedicated to the multi processes execution model is used

Looking at the code, it seems that you should be able to specify `threads`, `intelmpi`, `openmpi`, `srunmpi` or `default` here, with `default` being the default and being the one which runs single-threaded applications. It seems that maybe this hasn't been updated in a while? And/or perhaps that it was trying to say that anything other than `default` is only supported within a Slurm allocation, and not when running locally?

**Comment by pkopta** [comment]
Hi Lourens,
The updated documentation has been merged in #156 to the develop branch.

**Comment by LourensVeen** [comment]
Wonderful, thank you!
