### ISSUE TITLE
Change QCG-PilotJob dependency on zmq to PyZMQ

### ISSUE THREAD

**Issue by SimonPinches** [vecma-project/QCG-PilotJob#166]
QCG-PilotJob has a dependency on the `zmq` python package that is only available at version 0.0.0.   I suspect this dependency should really be on `PyZMQ` which provides the Python bindings to ZeroMQ.

**Comment by pkopta** [comment]
Hi @SimonPinches, thanks for reporting the problem. I will merge the fix asap.

**Comment by pkopta** [comment]
The fix was just merged into develop branch
