### ISSUE TITLE
Restart mechanisms for failed jobs due to external reasons such as job time out

### ISSUE THREAD

**Issue by satishskamath** [vecma-project/QCG-PilotJob#171]
Is there a restart mechanism for failed jobs? I could not find it in the documentation.

**Comment by pkopta** [comment]
Hi Satish,
Yes, we have a basic resume mechanism in QCG-PilotJob - it is documented at https://qcg-pilotjob.readthedocs.io/en/develop/resume.html.

**Comment by satishskamath** [comment]
Thanks I will try it and report if I find issues with it.
