### ISSUE TITLE
python executable not working correctly when setting venv in jobs.add()

### ISSUE THREAD

**Issue by dmark04** [vecma-project/QCG-PilotJob#174]
When using the optional arg `venv` in jobs.add() the executable is (imo) not picked up correctly.
E.g. when executing the two line python script:
```
import sys
print(f"Python interpreter: {sys.executable}")
```
and specifying `jobs.add(exec="python", venv="/path/to/my/venv")`

It just prints:
Python interpreter:
and does not pick up any of the packages installed in the specified venv.

Instead explicitly specifying `jobs.add(exec="/path/to/my/venv/bin/python", venv="/path/to/my/venv")`

Does print:
Python interpreter: /path/to/my/working_dir/-/path/to/my/venv/bin/python

which imo seems like a bug? Why would it join the path of my working directory there? (also I'm unfamiliar with the use of `/-/`)
Is the intended usage to clone a venv into the working directory of every job I add? 

Edit: 
Making a wrapper script
```
#!/bin/bash

source /path/to/my/venv/bin/activate
python "$@"
```
and passing that to `exec`
`jobs.add(exec="/path/to/wrapper.sh", venv="/path/to/my/venv")`
seems to fix it (although of course then passing `venv` is unnecessary)

**Comment by LourensVeen** [comment]
I'm running into the same issue, I think. the problem seems to be #163, since which QCG-PJ runs python using `exec -l`. Somehow, the `-l` option causes the virtualenv to be removed from `sys.path`, which is the list of directories where Python looks for modules to load, and so nothing is loaded. Plain `exec` without the `-l` doesn't seem to cause this problem.

**Comment by pkopta** [comment]
I came to the same conclusion as @LourensVeen after testing this issue. Removal of `-l` parameter from the `exec` command, should not affect execution of other models.

**Comment by pkopta** [comment]
This [branch](https://github.com/psnc-qcg/QCG-PilotJob/tree/issue-174_venv_interpreter) can be used to verify the problem has been solved.

**Comment by dmark04** [comment]
Sorry for the late reply, but I can confirm that the branch you provided @pkopta does solve my issue.

**Comment by dmark04** [comment]
@pkopta I am developing a python package to run optimization of scientific experiments on HPC based on qcgpilotjob. Would it be possible to release a new version of qcg-pilotjob on pypi that includes the changes from this issue?

**Comment by pkopta** [comment]
Hi @dmark04, we will try to release a new version within a few days.

**Comment by dmark04** [comment]
@pkopta any update on this?

**Comment by pkopta** [comment]
@dmark04 we have released a new version, but unfortunately we encountered problems with uploading packages to pypi - we probably need to change authorization scheme from password to token. We will try to solve this problem by tomorrow.

**Comment by pkopta** [comment]
@dmark04 0.14.1 version should be available now @ pypi.

**Comment by dmark04** [comment]
awesome thanks.
