### ISSUE TITLE
API documentation: finish(), cleanup() and wait4all() missing

### ISSUE THREAD

**Issue by LourensVeen** [vecma-project/QCG-PilotJob#62]
It seems that `qcg.appscheduler.api.manager.Manager` has `finish()`, `cleanup()` and `wait4all()` methods, but these are not mentioned in the README. I would like to know if they're part of the official public API, and see some documentation. In particular, I'm going to need `finish()` and probably `cleanup()`, while `wait4all()` would be nice to have. Oh, and in which order should `finish()` and `cleanup()` be called, if that matters?

**Comment by pkopta** [comment]
Hi Lourens, thanks for the comments. Yes, you are right, the documentation is bit out dated. I will try to document the recent changes soon.

**Comment by LourensVeen** [comment]
Can I recommend using Sphinx? Saves a lot of manual work, all you need is docstrings.

**Comment by pkopta** [comment]
We prepared documentation in rst format with sphinx and uploaded documentation to the readthedocs.io. In the current release 0.8 i rearanged the cleanup process in the manager classes.

**Comment by pkopta** [comment]
Hi @LourensVeen, can we close this issue ?

**Comment by LourensVeen** [comment]
Yes, looks really nice, well done! Thanks!
