### ISSUE TITLE
QCG-PilotJob should be on PyPI

### ISSUE THREAD

**Issue by LourensVeen** [vecma-project/QCG-PilotJob#63]
The installation instructions say to use pip to install directly from GitHub. This works well enough, but I'm not really sure what I'm getting here.

- Does installing from GitHub give me the latest release? Current development version? Something else?
- How do I install the latest stable version?
- How do I install a specific (fixed) version?
- Why isn't QCG-PilotJob on PyPI like everything else?

**Comment by pkopta** [comment]
Hi Lourens, the new release 0.8 is available now on pypi. We also uploaded documentation to the readthedocs.io

**Comment by pkopta** [comment]
Hi @LourensVeen, can we close this issue ?

**Comment by LourensVeen** [comment]
Yes, works great, thank you!
