### ISSUE TITLE
Starting QCG-PilotJob from a Python script

### ISSUE THREAD

**Issue by LourensVeen** [vecma-project/QCG-PilotJob#66]
If I want to start the service from a Python script, can I do that by instantiating and starting `QCGPMServiceProcess`? Is that part of the API (and will it therefore continue to work in newer versions), or is it an internal class that I'm not supposed to touch?

**Comment by pkopta** [comment]
Hi Lourens, we have prepared a new release 0.8 of QCG-PilotJob with updated documentation. For starting service in the background thread we have implemented qcg.pilotjob.api.manager.LocalManager class which underhood uses QCGPMServiceProcess. If you don't want the qcg.pilotjob.api.manager.Manager functionality you can use directly the QCGPMServiceProcess.

**Comment by LourensVeen** [comment]
That works for me, thanks!
