### ISSUE TITLE
CPU time: single job vs QCG-PilotJob 

### ISSUE THREAD

**Issue by jlakhlili** [vecma-project/QCG-PilotJob#77]
I did a simulation in **Eagle** cluster using EasyVVUQ-QCGPJ and It concerns 256 job, each one is  was running using MPI with 32 cores. 
The simulation was  launched with SLURM script using 6 nodes. When I checked the output of the first jobs (for example: ` execute_Run_1.stdout`), the CPU time for this job is around **43 mins** (and it is the same order for other jobs). 
```
 Main loop wall clock time:   2584.64944601059     
```   
But, When I run  one job of the same code using: `mpiexec -n 32 gem_test`, the CPU time around **3 mins.**
```
Main loop wall clock time:   184.894355058670     
```
It's a huge difference for the same program!

All logs, and scripts are in: `/home/plgrid-groups/plggvecma/Apps/Fusion/tests/qcgpj-cputime`.

**Comment by jlakhlili** [comment]
Hi @pkopta! 
I did the same tests in **Marconi** cluster and I had the same results (even worse) using MPI with 64 cores. 
I got around **3h 30 mins** for the execution each single job using QCGPJ when I got **1min 28s** for a single job  launched  directly via slurm using `mpiexec -n 64 gem_test`.

All logs, and scripts are in: `$WORK/qcgpj-gem_tests`

**Comment by pkopta** [comment]
Hi @jlakhlili, can you share with me the  `gem_test` test case i can use for tests ?

**Comment by jlakhlili** [comment]
Please find the `gem_test` and all inputs in:

- Eagle: `$VECMA_DIR/Apps/Fusion/tests/qcgpj-cputime/scripts`

- Marconi: `$WORK/qcgpj-gem_tests/scripts`

**Comment by pkopta** [comment]
Hi @jlakhlili, can you check your scenario with new release 0.9 of QCG-PilotJob. There are implemented new execution models for MPI applications: for Marconi cluster you can use for your IntelMPI applications 'intelmpi' or 'srunmpi' models, for the Eagle cluster you should use the 'intelmpi' model.

**Comment by jlakhlili** [comment]
Hi @pkopta,
I did several test with gem code mentioned above in **Marconi** Cluster.
Here is the change I did when I call Easyvvuq-Qcgpj Interface:
```
qcgpjexec.add_task(Task(
        TaskType.EXECUTION,
        TaskRequirements(cores=Resources(exact=ncores)),
        model='intelmpi',
        application=mpi_app
    ))
```
Where: `ncores=64` and `mpi_app=the_path_to_exec_gem_test`.
I have 256 samples, I want to run every samples with 64 MPI cores.
I used 20 nodes, each node contains 48 cores: 960 cores are available.

So, 960/64 = 15 first samples have to be run (normally it should took 3 mins).
But, we I look in the stderr logs, I find the following traces for the 15 runs:

```
cpu-bind=MAP  - r129c14s03, task  3  3 [22234]: mask 0x800000000 set
cpu-bind=MAP  - r129c14s03, task 10 10 [22241]: mask 0x40000000000 set
cpu-bind=MAP  - r129c14s03, task  0  0 [22231]: mask 0x100000000 set
cpu-bind=MAP  - r129c14s03, task 15 15 [22246]: mask 0x800000000000 set
cpu-bind=MAP  - r129c14s03, task  1  1 [22232]: mask 0x200000000 set
cpu-bind=MAP  - r129c14s03, task  2  2 [22233]: mask 0x400000000 set
cpu-bind=MAP  - r129c14s03, task  4  4 [22235]: mask 0x1000000000 set
cpu-bind=MAP  - r129c14s03, task  5  5 [22236]: mask 0x2000000000 set
....
```
And none of those 15 runs was executed!!!

You will find other logs in: `$WORK/qcgpj-logs`

PS. If I use mpi_app=tmpiexec -n 64 he_path_to_exec_gem_test`, just 10 run are executed but they took a long time, others run are executed and failed with this error:

`[43] MPI startup(): ofi fabric is not available and fallback fabric is not enabled`.

After discussion with @bartoszbosak, 
he suggested to use just `mpi_app=the_path_to_exec_gem_test` and not `mpiexec -n 64 ...`.

**Comment by pkopta** [comment]
Hi @jlakhlili, can you change the access rights to the `$WORK/qcgpj-logs` @ Marconi ?

**Comment by jlakhlili** [comment]
@pkopta Done!

**Comment by pkopta** [comment]
It seems that all the execute_Run_?? tasks has been submited to the QCG-PJ with the **`default`** model, not an `intelmpi` or `srunmpi` model. @bartoszbosak do you have any ideas why the model has not been passed from EasyVVUQ to the QCG-PJ ?

**Comment by jlakhlili** [comment]
Hi @pkopta,
After a slack discussion with @bartoszbosak, it seems that it was a versioning problem of *EQI* in my side.
Now, we fixed this and It works.
Thank you very much.
